### ISSUE TITLE
MONGO_URL support?

### ISSUE THREAD

**Issue by colllin** [okgrow/meteor-dotenv#2]
I can't seem to use the .env to specify the MONGO_URL.

Any way around this?  I can set other environment variables and access them using `process.env.NAMEHERE`  where `.env` contains `NAMEHERE=whatever`

But for `MONGO_URL`, I still see a `Starting MongoDB...` message when I start my app using `$ meteor`.  Also if I `console.log(process.env.MONGO_URL)`, I see `mongodb://127.0.0.1:3001/meteor` in my server logs.

**Comment by rgould** [comment]
When meteor loads, it sets `env.MONGO_URL` before the dotenv packages is even loaded [1]. Because `env.MONGO_URL` is already set when dotenv loads, it refuses to over-write the current value.

[1]: https://github.com/meteor/meteor/blob/1aba3a8e7ad8438c390249a31b27cf2d7562a3d5/tools/run-app.js#L168

Possible fixes:
1) Somehow load the dotenv package earlier than normal
2) Patch dotenv to permit forcing environment variables to be set.
3) Don't use dotenv as a Meteor package. Use another tool like Foreman (or shell script) to load `.env` before Meteor runs

@pauldowman Thoughts?

**Comment by pauldowman** [comment]
If anyone wants to investigate this and suggest a solution or provide a PR is consider it but I probably can't spend the effort to make it work otherwise.

**Comment by chrisbolin** [comment]
In case you are interested, I went ahead and used a simple shell script `serve.sh` to workaround this issue:

`export $(cat .env) && meteor`

This way `MONGO_URL`, `METEOR_SETTINGS`, etc. work. Not the prettiest, but it's functional.

**Comment by rgould** [comment]
We've deprecated this package, therefore we're closing all open issues.

**Comment by chrisblossom** [comment]
If anyone comes across this issue with dotenv + meteor, you can use ``npm scripts`` to solve the issue:
```json
  "scripts": {
    "dev": "env $(cat .env | xargs) meteor"
  },
```

All credit goes to [http://stackoverflow.com/questions/19331497/set-environment-variables-from-file](http://stackoverflow.com/questions/19331497/set-environment-variables-from-file)

Keep in mind this will only work for ``Linux/MacOS``.

*EDIT: changed ``npm run start`` to ``npm run dev``.

**Comment by pauldowman** [comment]
If that's your npm start script then make sure that's what you want on all environments including staging and production. Usually production environments have their own ways of setting env vars and you might not want it done via a file.

I recommend [direnv](https://direnv.net/) as a general solution.
