### ISSUE TITLE
no variables set after `meteor deploy`

### ISSUE THREAD

**Issue by bzz** [okgrow/meteor-dotenv#3]
May be I'm missing something: it works locally but on remote deployment using ```meteor deploy``` all env variables seems to be 'undefined'.

Is that expected behaviour or am I doing something wrong? 
Meteor 1.0.1

**Comment by rgould** [comment]
@bzz I talked to @pauldowman about this and we both agree that if you're going to use meteor.com for deployment, `Meteor.settings` should be used instead of `dotenv`. This package is really only intended to be used when a project is using a hosting service (such as Heroku) that expects configuration variables to be set as `ENV` variables. In that case, the `.env` file would let you use those same `ENV` variables in your development environment (and your `.env` file would not be deployed to the production environment).

**Comment by pauldowman** [comment]
That said, we would take a PR to fix it if you really want to.
