### ISSUE TITLE
Deprecation notice: how to use Meteor with npm's dotenv?

### ISSUE THREAD

**Issue by alejandroiglesias** [okgrow/meteor-dotenv#6]
I wanted to ask since you state in your deprecation notice: 

>Meteor 1.3's integration with npm has made this package obsolete. You can now use npm's dotenv directly, but our recommendation is to use direnv, as it doesn't require making modifications to your project.

Can you please provide more info on how to make Meteor use npm's dotenv? 
(direnv would be more hassle since would require to install and configure into developers' shells.)

Thanks a lot.

**Comment by pauldowman** [comment]
You can add the npm `dotenv` package directly in Meteor 1.3, follow the instructions here: https://www.npmjs.com/package/dotenv

If you have any problem with it not finding the `.env` file you can also do something like this: https://github.com/okgrow/meteor-dotenv/blob/master/lib/dotenv.js#L2

**Comment by alejandroiglesias** [comment]
Thanks for replying. Specifically, where should I put the `require('dotenv').config();` statement? At the top of `server/main.js` file? (Sorry, I'm new to Meteor.)
Thanks.

**Comment by pauldowman** [comment]
`server/main.js` would be a good place to configure it.

I haven't tried this package with Meteor 1.3+ since we use `direnv` but I assume it would be something like this:

```js
import dotenv from 'dotenv';
dotenv.config();
```

Or if `config()` can't find your `.env` file automatically due to the current working directory being different then instead of `config()` do what we did [here](https://github.com/okgrow/meteor-dotenv/blob/master/lib/dotenv.js#L2):

```js
dotenv._getKeysAndValuesFromEnvFilePath(process.env.PWD + "/.env");
dotenv._setEnvs();
```

For more info on using Npm packges in Meteor see https://guide.meteor.com/using-npm-packages.html

I hope this helps!

**Comment by alejandroiglesias** [comment]
Thanks a lot @pauldowman! Will try this out.
